apiVersion: v1
kind: ConfigMap
metadata:
  name: homer-config
data:
  config.yml: |
    # Homepage configuration
    # See https://fontawesome.com/icons for icons options

    title: "The Not Currently Broken Server"
    subtitle: "Dashboard"
    #logo: "logo.png"
    # icon: "fas fa-skull-crossbones" # Optional icon

    header: true
    footer: false 
    columns: "4"

    # Optional theme customization
    theme: default
    colors:
      light:
        highlight-primary: "#3367d6"
        highlight-secondary: "#4285f4"
        highlight-hover: "#5a95f5"
        background: "#f5f5f5"
        card-background: "#ffffff"
        text: "#363636"
        text-header: "#ffffff"
        text-title: "#303030"
        text-subtitle: "#424242"
        card-shadow: rgba(0, 0, 0, 0.1)
        link-hover: "#363636"
      dark:
        highlight-primary: "#3367d6"
        highlight-secondary: "#4285f4"
        highlight-hover: "#5a95f5"
        background: "#131313"
        card-background: "#2b2b2b"
        text: "#eaeaea"
        text-header: "#ffffff"
        text-title: "#fafafa"
        text-subtitle: "#f5f5f5"
        card-shadow: rgba(0, 0, 0, 0.4)
        link-hover: "#ffdd57"

    # Optional message
    #message:
    #  #url: https://b4bz.io
    #  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
    #  title: "Demo !"
    #  icon: "fa fa-grin"
    #  content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

    # Optional navbar
    # links: [] # Allows for navbar (dark mode, layout, and search) without any links
    links:
      - name: "Github"
        icon: "fab fa-github"
        url: "https://github.com/tanksrop"
        target: "_blank" # optional html a tag target attribute
      - name: "Wikipedia"
        icon: "fas fa-book"
        url: "https://www.wikipedia.org/"
      # this will link to a second homer page that will load config from additionnal-page.yml and keep default config values as in config.yml file
      # see url field and assets/additionnal-page.yml.dist used in this example:
      - name: "Hackaday"
        icon: "fas fa-file-alt"
        url: "https://hackaday.com" 

    # Services
    # First level array represent a group.
    # Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
    services:
      - name: "VMs"
        icon: "fas fa-cloud"
        items:
          - name: "Home Assistant"
            logo: "https://raw.githubusercontent.com/NX211/homer-icons/refs/heads/master/png/home-assistant.png"
            subtitle: "Home Automation"
            tag: "app"
            url: "http://192.168.0.55:8123"
            target: "_blank" # optional html a tag target attribute
          - name: "Truenas Scale"
            logo: "https://raw.githubusercontent.com/NX211/homer-icons/refs/heads/master/png/truenas.png"
            subtitle: "Storage"
            tag: "app"
            url: "http://192.168.0.81"
            target: "_blank" # optional html a tag target attribute
          - name: "FreePBX"
            logo: "https://raw.githubusercontent.com/NX211/homer-icons/refs/heads/master/png/freepbx.png"
            subtitle: "PBX"
            tag: "app"
            url: "http://192.168.0.78"
            target: "_blank" # optional html a tag target attribute
      - name: "Virtualization"
        icon: "fas fa-cloud"
        items:
          - name: "Proxmox"
            logo: "https://raw.githubusercontent.com/NX211/homer-icons/refs/heads/master/png/proxmox.png"
            subtitle: "Proxmox Virtualisation Environment"
            tag: "app"
            url: "https://192.168.0.46:8006"
            target: "_blank" # optional html a tag target attribute
      - name: "Media Server"
        icon: "fas fa-cloud"
        items:
          - name: "Jellyseerr"
            logo: "https://raw.githubusercontent.com/NX211/homer-icons/refs/heads/master/png/jellyseerr.png"
            subtitle: "Movies Requests"
            tag: "app"
            url: "http://jellyseerr.tanksrop.xyz"
          - name: "Jellyfin"
            logo: "https://raw.githubusercontent.com/NX211/homer-icons/refs/heads/master/png/jellyfin.png"
            subtitle: "Jellyfin Media Server"
            tag: "app"
            url: "http://jellyfin.tanksrop.xyz"
            target: "_blank" # optional html a tag target attribute
          - name: "Wizarr"
            logo: "https://raw.githubusercontent.com/NX211/homer-icons/refs/heads/master/png/wizarr.png"
            subtitle: "User Management"
            url: "http://wizarr.tanksrop.xyz"
            target: "_blank" # optional html a tag target attribute
            tag: "app"
          - name: "Radarr"
            logo: "https://raw.githubusercontent.com/NX211/homer-icons/refs/heads/master/png/radarr.png"
            subtitle: "Movie downloader"
            tag: "app"
            url: "http://radarr.local.tanksrop.xyz"
          - name: "Sonarr"
            logo: "https://raw.githubusercontent.com/NX211/homer-icons/refs/heads/master/png/sonarr.png"
            subtitle: "Shows downloader"
            tag: "app"
            url: "http://sonarr.local.tanksrop.xyz"
          - name: "Transmission"
            logo: "https://raw.githubusercontent.com/NX211/homer-icons/refs/heads/master/png/transmission.png"
            subtitle: "Torrent download client"
            tag: "app"
            url: "http://transmission.local.tanksrop.xyz"
          - name: "Sabnzbd"
            logo: "https://raw.githubusercontent.com/NX211/homer-icons/refs/heads/master/png/sabnzbd.png"
            subtitle: "Torrent download client"
            tag: "app"
            url: "http://sabnzbd.local.tanksrop.xyz"
          - name: "Prowlarr"
            logo: "https://raw.githubusercontent.com/NX211/homer-icons/refs/heads/master/png/prowlarr.png"
            subtitle: "Torrent Indexer"
            tag: "app"
            url: "http://prowlarr.local.tanksrop.xyz"
          - name: "huntarr"
            logo: "https://repository-images.githubusercontent.com/957479421/c936ef9e-79f0-4719-a42c-4a763cf43f76"
            subtitle: "Auto search for radarr and sonarr"
            tag: "app"
            url: "http://huntarr.local.tanksrop.xyz"
      - name: "Management"
        icon: "fas fa-cloud"
        items:
          - name: "ArgoCD"
            logo: "https://raw.githubusercontent.com/NX211/homer-icons/refs/heads/master/png/argocd.png"
            subtitle: "Git/Ops"
            tag: "app"
            url: "https://192.168.0.235:30080"